"""
Seed de verbos en inglés - Regulares e Irregulares
"""
from app import create_app
from app.extensions import db
from app.models import Verb, VerbTense

app = create_app()

# Lista de verbos con sus conjugaciones
verbs_data = [
    # ============================================
    # VERBOS AUXILIARES Y MODALES
    # ============================================
    {
        'infinitive': 'be',
        'past_simple': 'was/were',
        'past_participle': 'been',
        'present_participle': 'being',
        'third_person': 'is',
        'spanish_translation': 'ser, estar',
        'is_irregular': True,
        'is_auxiliary': True,
        'frequency_rank': 1,
        'difficulty': 'beginner',
        'category': 'auxiliary',
        'example_sentence': 'I am happy today.',
        'example_translation': 'Estoy feliz hoy.',
        'notes': 'Verbo más importante del inglés. Tiene formas únicas para cada pronombre.'
    },
    {
        'infinitive': 'have',
        'past_simple': 'had',
        'past_participle': 'had',
        'present_participle': 'having',
        'third_person': 'has',
        'spanish_translation': 'tener, haber',
        'is_irregular': True,
        'is_auxiliary': True,
        'frequency_rank': 2,
        'difficulty': 'beginner',
        'category': 'auxiliary',
        'example_sentence': 'She has two brothers.',
        'example_translation': 'Ella tiene dos hermanos.',
        'notes': 'Se usa como auxiliar en tiempos perfectos: I have eaten.'
    },
    {
        'infinitive': 'do',
        'past_simple': 'did',
        'past_participle': 'done',
        'present_participle': 'doing',
        'third_person': 'does',
        'spanish_translation': 'hacer',
        'is_irregular': True,
        'is_auxiliary': True,
        'frequency_rank': 3,
        'difficulty': 'beginner',
        'category': 'auxiliary',
        'example_sentence': 'What do you do for a living?',
        'example_translation': '¿A qué te dedicas?',
        'notes': 'Se usa como auxiliar para preguntas y negaciones en presente y pasado simple.'
    },
    {
        'infinitive': 'can',
        'past_simple': 'could',
        'past_participle': '-',
        'present_participle': '-',
        'third_person': 'can',
        'spanish_translation': 'poder (habilidad)',
        'is_irregular': True,
        'is_modal': True,
        'frequency_rank': 10,
        'difficulty': 'beginner',
        'category': 'modal',
        'example_sentence': 'I can swim very well.',
        'example_translation': 'Puedo nadar muy bien.',
        'notes': 'Modal para habilidad, permiso y posibilidad. No cambia con tercera persona.'
    },
    {
        'infinitive': 'will',
        'past_simple': 'would',
        'past_participle': '-',
        'present_participle': '-',
        'third_person': 'will',
        'spanish_translation': 'voluntad, futuro',
        'is_irregular': True,
        'is_modal': True,
        'frequency_rank': 11,
        'difficulty': 'beginner',
        'category': 'modal',
        'example_sentence': 'I will call you tomorrow.',
        'example_translation': 'Te llamaré mañana.',
        'notes': 'Se usa para futuro simple y promesas/decisiones espontáneas.'
    },
    {
        'infinitive': 'must',
        'past_simple': 'had to',
        'past_participle': '-',
        'present_participle': '-',
        'third_person': 'must',
        'spanish_translation': 'deber (obligación)',
        'is_irregular': True,
        'is_modal': True,
        'frequency_rank': 25,
        'difficulty': 'beginner',
        'category': 'modal',
        'example_sentence': 'You must wear a seatbelt.',
        'example_translation': 'Debes usar el cinturón de seguridad.',
        'notes': 'Expresa obligación fuerte o deducción lógica.'
    },
    {
        'infinitive': 'should',
        'past_simple': 'should have',
        'past_participle': '-',
        'present_participle': '-',
        'third_person': 'should',
        'spanish_translation': 'debería (consejo)',
        'is_irregular': True,
        'is_modal': True,
        'frequency_rank': 26,
        'difficulty': 'beginner',
        'category': 'modal',
        'example_sentence': 'You should study more.',
        'example_translation': 'Deberías estudiar más.',
        'notes': 'Se usa para dar consejos o recomendaciones.'
    },
    {
        'infinitive': 'may',
        'past_simple': 'might',
        'past_participle': '-',
        'present_participle': '-',
        'third_person': 'may',
        'spanish_translation': 'poder (posibilidad/permiso)',
        'is_irregular': True,
        'is_modal': True,
        'frequency_rank': 30,
        'difficulty': 'intermediate',
        'category': 'modal',
        'example_sentence': 'It may rain tomorrow.',
        'example_translation': 'Puede que llueva mañana.',
        'notes': 'Expresa posibilidad o permiso formal.'
    },
    
    # ============================================
    # VERBOS IRREGULARES COMUNES
    # ============================================
    {
        'infinitive': 'go',
        'past_simple': 'went',
        'past_participle': 'gone',
        'present_participle': 'going',
        'third_person': 'goes',
        'spanish_translation': 'ir',
        'is_irregular': True,
        'frequency_rank': 4,
        'difficulty': 'beginner',
        'category': 'movement',
        'example_sentence': 'I go to school every day.',
        'example_translation': 'Voy a la escuela todos los días.',
        'notes': 'Uno de los verbos más usados. "Going to" se usa para planes futuros.'
    },
    {
        'infinitive': 'get',
        'past_simple': 'got',
        'past_participle': 'got/gotten',
        'present_participle': 'getting',
        'third_person': 'gets',
        'spanish_translation': 'obtener, conseguir, llegar',
        'is_irregular': True,
        'frequency_rank': 5,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I got a new job.',
        'example_translation': 'Conseguí un nuevo trabajo.',
        'notes': 'Verbo muy versátil con muchos significados según el contexto.'
    },
    {
        'infinitive': 'make',
        'past_simple': 'made',
        'past_participle': 'made',
        'present_participle': 'making',
        'third_person': 'makes',
        'spanish_translation': 'hacer, fabricar',
        'is_irregular': True,
        'frequency_rank': 6,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'She makes delicious cakes.',
        'example_translation': 'Ella hace pasteles deliciosos.',
        'notes': 'Make = crear algo. Do = realizar una acción.'
    },
    {
        'infinitive': 'say',
        'past_simple': 'said',
        'past_participle': 'said',
        'present_participle': 'saying',
        'third_person': 'says',
        'spanish_translation': 'decir',
        'is_irregular': True,
        'frequency_rank': 7,
        'difficulty': 'beginner',
        'category': 'communication',
        'example_sentence': 'He said he was tired.',
        'example_translation': 'Él dijo que estaba cansado.',
        'notes': 'Say = decir (énfasis en palabras). Tell = contar (a alguien).'
    },
    {
        'infinitive': 'know',
        'past_simple': 'knew',
        'past_participle': 'known',
        'present_participle': 'knowing',
        'third_person': 'knows',
        'spanish_translation': 'saber, conocer',
        'is_irregular': True,
        'frequency_rank': 8,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I know the answer.',
        'example_translation': 'Sé la respuesta.',
        'notes': 'Verbo de estado - no se usa en forma continua normalmente.'
    },
    {
        'infinitive': 'think',
        'past_simple': 'thought',
        'past_participle': 'thought',
        'present_participle': 'thinking',
        'third_person': 'thinks',
        'spanish_translation': 'pensar, creer',
        'is_irregular': True,
        'frequency_rank': 9,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I think this is a good idea.',
        'example_translation': 'Creo que es una buena idea.',
        'notes': 'Se usa para expresar opiniones y procesos mentales.'
    },
    {
        'infinitive': 'see',
        'past_simple': 'saw',
        'past_participle': 'seen',
        'present_participle': 'seeing',
        'third_person': 'sees',
        'spanish_translation': 'ver',
        'is_irregular': True,
        'frequency_rank': 12,
        'difficulty': 'beginner',
        'category': 'perception',
        'example_sentence': 'I saw a beautiful sunset.',
        'example_translation': 'Vi un hermoso atardecer.',
        'notes': 'See = percibir. Watch = mirar con atención. Look = dirigir la mirada.'
    },
    {
        'infinitive': 'come',
        'past_simple': 'came',
        'past_participle': 'come',
        'present_participle': 'coming',
        'third_person': 'comes',
        'spanish_translation': 'venir',
        'is_irregular': True,
        'frequency_rank': 13,
        'difficulty': 'beginner',
        'category': 'movement',
        'example_sentence': 'Please come to my party.',
        'example_translation': 'Por favor ven a mi fiesta.',
        'notes': 'Come = movimiento hacia el hablante. Go = movimiento alejándose.'
    },
    {
        'infinitive': 'take',
        'past_simple': 'took',
        'past_participle': 'taken',
        'present_participle': 'taking',
        'third_person': 'takes',
        'spanish_translation': 'tomar, llevar',
        'is_irregular': True,
        'frequency_rank': 14,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Take your umbrella with you.',
        'example_translation': 'Lleva tu paraguas contigo.',
        'notes': 'Verbo muy versátil: take a photo, take a shower, take time.'
    },
    {
        'infinitive': 'give',
        'past_simple': 'gave',
        'past_participle': 'given',
        'present_participle': 'giving',
        'third_person': 'gives',
        'spanish_translation': 'dar',
        'is_irregular': True,
        'frequency_rank': 15,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Give me a call later.',
        'example_translation': 'Llámame luego.',
        'notes': 'Puede tener dos objetos: Give me (IO) the book (DO).'
    },
    {
        'infinitive': 'find',
        'past_simple': 'found',
        'past_participle': 'found',
        'present_participle': 'finding',
        'third_person': 'finds',
        'spanish_translation': 'encontrar',
        'is_irregular': True,
        'frequency_rank': 16,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I found my keys!',
        'example_translation': '¡Encontré mis llaves!',
        'notes': 'También se usa para expresar opiniones: I find it interesting.'
    },
    {
        'infinitive': 'tell',
        'past_simple': 'told',
        'past_participle': 'told',
        'present_participle': 'telling',
        'third_person': 'tells',
        'spanish_translation': 'contar, decir a alguien',
        'is_irregular': True,
        'frequency_rank': 17,
        'difficulty': 'beginner',
        'category': 'communication',
        'example_sentence': 'Tell me the truth.',
        'example_translation': 'Dime la verdad.',
        'notes': 'Tell siempre necesita objeto: Tell me, tell her. Say no lo necesita.'
    },
    {
        'infinitive': 'feel',
        'past_simple': 'felt',
        'past_participle': 'felt',
        'present_participle': 'feeling',
        'third_person': 'feels',
        'spanish_translation': 'sentir',
        'is_irregular': True,
        'frequency_rank': 18,
        'difficulty': 'beginner',
        'category': 'perception',
        'example_sentence': 'I feel happy today.',
        'example_translation': 'Me siento feliz hoy.',
        'notes': 'Se usa para emociones y sensaciones físicas.'
    },
    {
        'infinitive': 'become',
        'past_simple': 'became',
        'past_participle': 'become',
        'present_participle': 'becoming',
        'third_person': 'becomes',
        'spanish_translation': 'convertirse en, llegar a ser',
        'is_irregular': True,
        'frequency_rank': 19,
        'difficulty': 'intermediate',
        'category': 'linking',
        'example_sentence': 'She became a doctor.',
        'example_translation': 'Ella se convirtió en doctora.',
        'notes': 'Verbo de enlace - seguido de adjetivo o sustantivo.'
    },
    {
        'infinitive': 'leave',
        'past_simple': 'left',
        'past_participle': 'left',
        'present_participle': 'leaving',
        'third_person': 'leaves',
        'spanish_translation': 'dejar, salir, irse',
        'is_irregular': True,
        'frequency_rank': 20,
        'difficulty': 'beginner',
        'category': 'movement',
        'example_sentence': 'I left my bag at home.',
        'example_translation': 'Dejé mi bolso en casa.',
        'notes': 'Leave = irse/dejar. Leave for = partir hacia.'
    },
    {
        'infinitive': 'put',
        'past_simple': 'put',
        'past_participle': 'put',
        'present_participle': 'putting',
        'third_person': 'puts',
        'spanish_translation': 'poner, colocar',
        'is_irregular': True,
        'frequency_rank': 21,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Put the book on the table.',
        'example_translation': 'Pon el libro en la mesa.',
        'notes': 'El pasado y participio son iguales al infinitivo.'
    },
    {
        'infinitive': 'read',
        'past_simple': 'read',
        'past_participle': 'read',
        'present_participle': 'reading',
        'third_person': 'reads',
        'spanish_translation': 'leer',
        'is_irregular': True,
        'frequency_rank': 22,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I read a book every week.',
        'example_translation': 'Leo un libro cada semana.',
        'notes': 'La forma pasada se pronuncia /red/ (como "red").'
    },
    {
        'infinitive': 'write',
        'past_simple': 'wrote',
        'past_participle': 'written',
        'present_participle': 'writing',
        'third_person': 'writes',
        'spanish_translation': 'escribir',
        'is_irregular': True,
        'frequency_rank': 23,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'She writes beautiful poems.',
        'example_translation': 'Ella escribe hermosos poemas.',
        'notes': 'Write down = anotar. Write to = escribir a (alguien).'
    },
    {
        'infinitive': 'run',
        'past_simple': 'ran',
        'past_participle': 'run',
        'present_participle': 'running',
        'third_person': 'runs',
        'spanish_translation': 'correr',
        'is_irregular': True,
        'frequency_rank': 24,
        'difficulty': 'beginner',
        'category': 'movement',
        'example_sentence': 'He runs every morning.',
        'example_translation': 'Él corre todas las mañanas.',
        'notes': 'También: run a business = dirigir un negocio.'
    },
    {
        'infinitive': 'bring',
        'past_simple': 'brought',
        'past_participle': 'brought',
        'present_participle': 'bringing',
        'third_person': 'brings',
        'spanish_translation': 'traer',
        'is_irregular': True,
        'frequency_rank': 27,
        'difficulty': 'beginner',
        'category': 'movement',
        'example_sentence': 'Bring your ID tomorrow.',
        'example_translation': 'Trae tu identificación mañana.',
        'notes': 'Bring = traer (hacia el hablante). Take = llevar (alejándose).'
    },
    {
        'infinitive': 'buy',
        'past_simple': 'bought',
        'past_participle': 'bought',
        'present_participle': 'buying',
        'third_person': 'buys',
        'spanish_translation': 'comprar',
        'is_irregular': True,
        'frequency_rank': 28,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I bought a new car.',
        'example_translation': 'Compré un auto nuevo.',
        'notes': 'Buy from = comprar de. Buy for = comprar para.'
    },
    {
        'infinitive': 'eat',
        'past_simple': 'ate',
        'past_participle': 'eaten',
        'present_participle': 'eating',
        'third_person': 'eats',
        'spanish_translation': 'comer',
        'is_irregular': True,
        'frequency_rank': 29,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'We eat dinner at 7 PM.',
        'example_translation': 'Cenamos a las 7 PM.',
        'notes': 'Eat out = comer fuera. Eat up = comer todo.'
    },
    {
        'infinitive': 'drink',
        'past_simple': 'drank',
        'past_participle': 'drunk',
        'present_participle': 'drinking',
        'third_person': 'drinks',
        'spanish_translation': 'beber',
        'is_irregular': True,
        'frequency_rank': 31,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I drink coffee every morning.',
        'example_translation': 'Bebo café todas las mañanas.',
        'notes': 'Drunk también es adjetivo (ebrio).'
    },
    {
        'infinitive': 'speak',
        'past_simple': 'spoke',
        'past_participle': 'spoken',
        'present_participle': 'speaking',
        'third_person': 'speaks',
        'spanish_translation': 'hablar',
        'is_irregular': True,
        'frequency_rank': 32,
        'difficulty': 'beginner',
        'category': 'communication',
        'example_sentence': 'Do you speak English?',
        'example_translation': '¿Hablas inglés?',
        'notes': 'Speak = hablar (idiomas, formal). Talk = charlar, conversar.'
    },
    {
        'infinitive': 'meet',
        'past_simple': 'met',
        'past_participle': 'met',
        'present_participle': 'meeting',
        'third_person': 'meets',
        'spanish_translation': 'conocer, encontrarse',
        'is_irregular': True,
        'frequency_rank': 33,
        'difficulty': 'beginner',
        'category': 'social',
        'example_sentence': 'Nice to meet you!',
        'example_translation': '¡Mucho gusto!',
        'notes': 'Meet = conocer por primera vez o encontrarse.'
    },
    {
        'infinitive': 'hear',
        'past_simple': 'heard',
        'past_participle': 'heard',
        'present_participle': 'hearing',
        'third_person': 'hears',
        'spanish_translation': 'oír',
        'is_irregular': True,
        'frequency_rank': 34,
        'difficulty': 'beginner',
        'category': 'perception',
        'example_sentence': 'Did you hear that noise?',
        'example_translation': '¿Oíste ese ruido?',
        'notes': 'Hear = percibir sonido. Listen = escuchar con atención.'
    },
    {
        'infinitive': 'keep',
        'past_simple': 'kept',
        'past_participle': 'kept',
        'present_participle': 'keeping',
        'third_person': 'keeps',
        'spanish_translation': 'mantener, guardar',
        'is_irregular': True,
        'frequency_rank': 35,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Keep the change.',
        'example_translation': 'Quédate con el cambio.',
        'notes': 'Keep + gerundio = continuar haciendo algo.'
    },
    {
        'infinitive': 'let',
        'past_simple': 'let',
        'past_participle': 'let',
        'present_participle': 'letting',
        'third_person': 'lets',
        'spanish_translation': 'dejar, permitir',
        'is_irregular': True,
        'frequency_rank': 36,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': "Let me help you.",
        'example_translation': 'Déjame ayudarte.',
        'notes': 'Let + objeto + infinitivo sin to: Let me go.'
    },
    {
        'infinitive': 'begin',
        'past_simple': 'began',
        'past_participle': 'begun',
        'present_participle': 'beginning',
        'third_person': 'begins',
        'spanish_translation': 'comenzar, empezar',
        'is_irregular': True,
        'frequency_rank': 37,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'The class begins at 9 AM.',
        'example_translation': 'La clase comienza a las 9 AM.',
        'notes': 'Begin y start son sinónimos. Begin es más formal.'
    },
    {
        'infinitive': 'sit',
        'past_simple': 'sat',
        'past_participle': 'sat',
        'present_participle': 'sitting',
        'third_person': 'sits',
        'spanish_translation': 'sentarse',
        'is_irregular': True,
        'frequency_rank': 38,
        'difficulty': 'beginner',
        'category': 'position',
        'example_sentence': 'Please sit down.',
        'example_translation': 'Por favor siéntate.',
        'notes': 'Sit down = sentarse. Sit up = incorporarse.'
    },
    {
        'infinitive': 'stand',
        'past_simple': 'stood',
        'past_participle': 'stood',
        'present_participle': 'standing',
        'third_person': 'stands',
        'spanish_translation': 'estar de pie, pararse',
        'is_irregular': True,
        'frequency_rank': 39,
        'difficulty': 'beginner',
        'category': 'position',
        'example_sentence': 'Stand up, please.',
        'example_translation': 'Levántate, por favor.',
        'notes': 'Stand for = representar. Stand out = destacar.'
    },
    {
        'infinitive': 'lose',
        'past_simple': 'lost',
        'past_participle': 'lost',
        'present_participle': 'losing',
        'third_person': 'loses',
        'spanish_translation': 'perder',
        'is_irregular': True,
        'frequency_rank': 40,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I lost my wallet.',
        'example_translation': 'Perdí mi billetera.',
        'notes': 'Lose (perder) vs Loose (suelto/flojo) - diferente pronunciación.'
    },
    {
        'infinitive': 'pay',
        'past_simple': 'paid',
        'past_participle': 'paid',
        'present_participle': 'paying',
        'third_person': 'pays',
        'spanish_translation': 'pagar',
        'is_irregular': True,
        'frequency_rank': 41,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I paid the bill.',
        'example_translation': 'Pagué la cuenta.',
        'notes': 'Pay for = pagar por algo. Pay attention = prestar atención.'
    },
    {
        'infinitive': 'send',
        'past_simple': 'sent',
        'past_participle': 'sent',
        'present_participle': 'sending',
        'third_person': 'sends',
        'spanish_translation': 'enviar',
        'is_irregular': True,
        'frequency_rank': 42,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I sent you an email.',
        'example_translation': 'Te envié un correo.',
        'notes': 'Send for = mandar a buscar. Send back = devolver.'
    },
    {
        'infinitive': 'build',
        'past_simple': 'built',
        'past_participle': 'built',
        'present_participle': 'building',
        'third_person': 'builds',
        'spanish_translation': 'construir',
        'is_irregular': True,
        'frequency_rank': 43,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'They built a new house.',
        'example_translation': 'Construyeron una casa nueva.',
        'notes': 'Build up = acumular. Build on = basarse en.'
    },
    {
        'infinitive': 'spend',
        'past_simple': 'spent',
        'past_participle': 'spent',
        'present_participle': 'spending',
        'third_person': 'spends',
        'spanish_translation': 'gastar, pasar (tiempo)',
        'is_irregular': True,
        'frequency_rank': 44,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I spent all my money.',
        'example_translation': 'Gasté todo mi dinero.',
        'notes': 'Spend time = pasar tiempo. Spend money = gastar dinero.'
    },
    {
        'infinitive': 'fall',
        'past_simple': 'fell',
        'past_participle': 'fallen',
        'present_participle': 'falling',
        'third_person': 'falls',
        'spanish_translation': 'caer',
        'is_irregular': True,
        'frequency_rank': 45,
        'difficulty': 'beginner',
        'category': 'movement',
        'example_sentence': 'The leaves fall in autumn.',
        'example_translation': 'Las hojas caen en otoño.',
        'notes': 'Fall asleep = dormirse. Fall in love = enamorarse.'
    },
    {
        'infinitive': 'cut',
        'past_simple': 'cut',
        'past_participle': 'cut',
        'present_participle': 'cutting',
        'third_person': 'cuts',
        'spanish_translation': 'cortar',
        'is_irregular': True,
        'frequency_rank': 46,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Cut the paper in half.',
        'example_translation': 'Corta el papel a la mitad.',
        'notes': 'Las tres formas son iguales: cut/cut/cut.'
    },
    {
        'infinitive': 'catch',
        'past_simple': 'caught',
        'past_participle': 'caught',
        'present_participle': 'catching',
        'third_person': 'catches',
        'spanish_translation': 'atrapar, coger',
        'is_irregular': True,
        'frequency_rank': 47,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Catch the ball!',
        'example_translation': '¡Atrapa la pelota!',
        'notes': 'Catch a cold = resfriarse. Catch a bus = tomar un bus.'
    },
    {
        'infinitive': 'teach',
        'past_simple': 'taught',
        'past_participle': 'taught',
        'present_participle': 'teaching',
        'third_person': 'teaches',
        'spanish_translation': 'enseñar',
        'is_irregular': True,
        'frequency_rank': 48,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'She teaches English.',
        'example_translation': 'Ella enseña inglés.',
        'notes': 'Teach someone (to do) something.'
    },
    {
        'infinitive': 'sell',
        'past_simple': 'sold',
        'past_participle': 'sold',
        'present_participle': 'selling',
        'third_person': 'sells',
        'spanish_translation': 'vender',
        'is_irregular': True,
        'frequency_rank': 49,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'They sell fresh vegetables.',
        'example_translation': 'Ellos venden vegetales frescos.',
        'notes': 'Sell to = vender a (persona). Sell for = vender por (precio).'
    },
    {
        'infinitive': 'sleep',
        'past_simple': 'slept',
        'past_participle': 'slept',
        'present_participle': 'sleeping',
        'third_person': 'sleeps',
        'spanish_translation': 'dormir',
        'is_irregular': True,
        'frequency_rank': 50,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I slept 8 hours.',
        'example_translation': 'Dormí 8 horas.',
        'notes': 'Go to sleep = ir a dormir. Fall asleep = quedarse dormido.'
    },
    
    # ============================================
    # VERBOS REGULARES COMUNES
    # ============================================
    {
        'infinitive': 'work',
        'past_simple': 'worked',
        'past_participle': 'worked',
        'present_participle': 'working',
        'third_person': 'works',
        'spanish_translation': 'trabajar',
        'is_irregular': False,
        'frequency_rank': 51,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I work from home.',
        'example_translation': 'Trabajo desde casa.',
        'notes': 'Work on = trabajar en. Work out = hacer ejercicio / resolver.'
    },
    {
        'infinitive': 'play',
        'past_simple': 'played',
        'past_participle': 'played',
        'present_participle': 'playing',
        'third_person': 'plays',
        'spanish_translation': 'jugar, tocar (instrumento)',
        'is_irregular': False,
        'frequency_rank': 52,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'She plays the piano.',
        'example_translation': 'Ella toca el piano.',
        'notes': 'Play sports/games. Play + instrumento musical.'
    },
    {
        'infinitive': 'want',
        'past_simple': 'wanted',
        'past_participle': 'wanted',
        'present_participle': 'wanting',
        'third_person': 'wants',
        'spanish_translation': 'querer',
        'is_irregular': False,
        'frequency_rank': 53,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I want to learn English.',
        'example_translation': 'Quiero aprender inglés.',
        'notes': 'Want + to + infinitivo. No se usa normalmente en continuo.'
    },
    {
        'infinitive': 'need',
        'past_simple': 'needed',
        'past_participle': 'needed',
        'present_participle': 'needing',
        'third_person': 'needs',
        'spanish_translation': 'necesitar',
        'is_irregular': False,
        'frequency_rank': 54,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I need your help.',
        'example_translation': 'Necesito tu ayuda.',
        'notes': 'Need + to + infinitivo. Need + sustantivo.'
    },
    {
        'infinitive': 'like',
        'past_simple': 'liked',
        'past_participle': 'liked',
        'present_participle': 'liking',
        'third_person': 'likes',
        'spanish_translation': 'gustar',
        'is_irregular': False,
        'frequency_rank': 55,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I like pizza.',
        'example_translation': 'Me gusta la pizza.',
        'notes': 'Like + sustantivo / Like + gerundio / Like + to + infinitivo.'
    },
    {
        'infinitive': 'love',
        'past_simple': 'loved',
        'past_participle': 'loved',
        'present_participle': 'loving',
        'third_person': 'loves',
        'spanish_translation': 'amar, encantar',
        'is_irregular': False,
        'frequency_rank': 56,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I love this song.',
        'example_translation': 'Me encanta esta canción.',
        'notes': 'Más fuerte que "like". Se usa para expresar amor o gusto intenso.'
    },
    {
        'infinitive': 'live',
        'past_simple': 'lived',
        'past_participle': 'lived',
        'present_participle': 'living',
        'third_person': 'lives',
        'spanish_translation': 'vivir',
        'is_irregular': False,
        'frequency_rank': 57,
        'difficulty': 'beginner',
        'category': 'state',
        'example_sentence': 'I live in Mexico City.',
        'example_translation': 'Vivo en Ciudad de México.',
        'notes': 'Live in + ciudad/país. Live at + dirección.'
    },
    {
        'infinitive': 'walk',
        'past_simple': 'walked',
        'past_participle': 'walked',
        'present_participle': 'walking',
        'third_person': 'walks',
        'spanish_translation': 'caminar',
        'is_irregular': False,
        'frequency_rank': 58,
        'difficulty': 'beginner',
        'category': 'movement',
        'example_sentence': 'I walk to school.',
        'example_translation': 'Camino a la escuela.',
        'notes': 'Walk + to + lugar = ir caminando a.'
    },
    {
        'infinitive': 'talk',
        'past_simple': 'talked',
        'past_participle': 'talked',
        'present_participle': 'talking',
        'third_person': 'talks',
        'spanish_translation': 'hablar, charlar',
        'is_irregular': False,
        'frequency_rank': 59,
        'difficulty': 'beginner',
        'category': 'communication',
        'example_sentence': 'We need to talk.',
        'example_translation': 'Necesitamos hablar.',
        'notes': 'Talk to/with someone. Talk about something.'
    },
    {
        'infinitive': 'ask',
        'past_simple': 'asked',
        'past_participle': 'asked',
        'present_participle': 'asking',
        'third_person': 'asks',
        'spanish_translation': 'preguntar, pedir',
        'is_irregular': False,
        'frequency_rank': 60,
        'difficulty': 'beginner',
        'category': 'communication',
        'example_sentence': 'Can I ask you a question?',
        'example_translation': '¿Puedo hacerte una pregunta?',
        'notes': 'Ask someone a question. Ask for something.'
    },
    {
        'infinitive': 'help',
        'past_simple': 'helped',
        'past_participle': 'helped',
        'present_participle': 'helping',
        'third_person': 'helps',
        'spanish_translation': 'ayudar',
        'is_irregular': False,
        'frequency_rank': 61,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Can you help me?',
        'example_translation': '¿Puedes ayudarme?',
        'notes': 'Help + objeto + (to) + infinitivo.'
    },
    {
        'infinitive': 'look',
        'past_simple': 'looked',
        'past_participle': 'looked',
        'present_participle': 'looking',
        'third_person': 'looks',
        'spanish_translation': 'mirar, parecer',
        'is_irregular': False,
        'frequency_rank': 62,
        'difficulty': 'beginner',
        'category': 'perception',
        'example_sentence': 'Look at this picture.',
        'example_translation': 'Mira esta foto.',
        'notes': 'Look at = mirar. Look for = buscar. Look like = parecerse a.'
    },
    {
        'infinitive': 'wait',
        'past_simple': 'waited',
        'past_participle': 'waited',
        'present_participle': 'waiting',
        'third_person': 'waits',
        'spanish_translation': 'esperar',
        'is_irregular': False,
        'frequency_rank': 63,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Wait for me, please.',
        'example_translation': 'Espérame, por favor.',
        'notes': 'Wait for + persona/cosa.'
    },
    {
        'infinitive': 'call',
        'past_simple': 'called',
        'past_participle': 'called',
        'present_participle': 'calling',
        'third_person': 'calls',
        'spanish_translation': 'llamar',
        'is_irregular': False,
        'frequency_rank': 64,
        'difficulty': 'beginner',
        'category': 'communication',
        'example_sentence': 'I will call you later.',
        'example_translation': 'Te llamaré después.',
        'notes': 'Call someone = llamar por teléfono. Be called = llamarse.'
    },
    {
        'infinitive': 'use',
        'past_simple': 'used',
        'past_participle': 'used',
        'present_participle': 'using',
        'third_person': 'uses',
        'spanish_translation': 'usar',
        'is_irregular': False,
        'frequency_rank': 65,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I use my phone every day.',
        'example_translation': 'Uso mi teléfono todos los días.',
        'notes': 'Used to = solía (hábito pasado).'
    },
    {
        'infinitive': 'try',
        'past_simple': 'tried',
        'past_participle': 'tried',
        'present_participle': 'trying',
        'third_person': 'tries',
        'spanish_translation': 'intentar, probar',
        'is_irregular': False,
        'frequency_rank': 66,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Try again!',
        'example_translation': '¡Inténtalo de nuevo!',
        'notes': 'Try + to + infinitivo (intentar). Try + gerundio (probar).'
    },
    {
        'infinitive': 'start',
        'past_simple': 'started',
        'past_participle': 'started',
        'present_participle': 'starting',
        'third_person': 'starts',
        'spanish_translation': 'empezar, comenzar',
        'is_irregular': False,
        'frequency_rank': 67,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': "Let's start the meeting.",
        'example_translation': 'Comencemos la reunión.',
        'notes': 'Start + gerundio o start + to + infinitivo.'
    },
    {
        'infinitive': 'stop',
        'past_simple': 'stopped',
        'past_participle': 'stopped',
        'present_participle': 'stopping',
        'third_person': 'stops',
        'spanish_translation': 'parar, detenerse',
        'is_irregular': False,
        'frequency_rank': 68,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Stop talking, please.',
        'example_translation': 'Deja de hablar, por favor.',
        'notes': 'Stop + gerundio = dejar de hacer algo.'
    },
    {
        'infinitive': 'learn',
        'past_simple': 'learned/learnt',
        'past_participle': 'learned/learnt',
        'present_participle': 'learning',
        'third_person': 'learns',
        'spanish_translation': 'aprender',
        'is_irregular': False,
        'frequency_rank': 69,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': "I'm learning Spanish.",
        'example_translation': 'Estoy aprendiendo español.',
        'notes': 'Learned (US) / Learnt (UK). Learn + to + infinitivo.'
    },
    {
        'infinitive': 'study',
        'past_simple': 'studied',
        'past_participle': 'studied',
        'present_participle': 'studying',
        'third_person': 'studies',
        'spanish_translation': 'estudiar',
        'is_irregular': False,
        'frequency_rank': 70,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I study English every day.',
        'example_translation': 'Estudio inglés todos los días.',
        'notes': 'Study for = estudiar para (examen).'
    },
    {
        'infinitive': 'watch',
        'past_simple': 'watched',
        'past_participle': 'watched',
        'present_participle': 'watching',
        'third_person': 'watches',
        'spanish_translation': 'ver (con atención), observar',
        'is_irregular': False,
        'frequency_rank': 71,
        'difficulty': 'beginner',
        'category': 'perception',
        'example_sentence': 'I watch TV every night.',
        'example_translation': 'Veo televisión cada noche.',
        'notes': 'Watch = mirar con atención (TV, partido). See = percibir.'
    },
    {
        'infinitive': 'listen',
        'past_simple': 'listened',
        'past_participle': 'listened',
        'present_participle': 'listening',
        'third_person': 'listens',
        'spanish_translation': 'escuchar',
        'is_irregular': False,
        'frequency_rank': 72,
        'difficulty': 'beginner',
        'category': 'perception',
        'example_sentence': 'Listen to this song.',
        'example_translation': 'Escucha esta canción.',
        'notes': 'Listen to + música/persona. Hear = percibir sonido.'
    },
    {
        'infinitive': 'open',
        'past_simple': 'opened',
        'past_participle': 'opened',
        'present_participle': 'opening',
        'third_person': 'opens',
        'spanish_translation': 'abrir',
        'is_irregular': False,
        'frequency_rank': 73,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Open the door, please.',
        'example_translation': 'Abre la puerta, por favor.',
        'notes': 'También adjetivo: The store is open.'
    },
    {
        'infinitive': 'close',
        'past_simple': 'closed',
        'past_participle': 'closed',
        'present_participle': 'closing',
        'third_person': 'closes',
        'spanish_translation': 'cerrar',
        'is_irregular': False,
        'frequency_rank': 74,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'Close your eyes.',
        'example_translation': 'Cierra los ojos.',
        'notes': 'También adjetivo: The store is closed.'
    },
    {
        'infinitive': 'finish',
        'past_simple': 'finished',
        'past_participle': 'finished',
        'present_participle': 'finishing',
        'third_person': 'finishes',
        'spanish_parses_translation': 'terminar',
        'spanish_translation': 'terminar',
        'is_irregular': False,
        'frequency_rank': 75,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I finished my homework.',
        'example_translation': 'Terminé mi tarea.',
        'notes': 'Finish + gerundio = terminar de hacer algo.'
    },
    {
        'infinitive': 'change',
        'past_simple': 'changed',
        'past_participle': 'changed',
        'present_participle': 'changing',
        'third_person': 'changes',
        'spanish_translation': 'cambiar',
        'is_irregular': False,
        'frequency_rank': 76,
        'difficulty': 'beginner',
        'category': 'action',
        'example_sentence': 'I changed my mind.',
        'example_translation': 'Cambié de opinión.',
        'notes': 'Change your mind = cambiar de opinión.'
    },
    {
        'infinitive': 'move',
        'past_simple': 'moved',
        'past_participle': 'moved',
        'present_participle': 'moving',
        'third_person': 'moves',
        'spanish_translation': 'mover, mudarse',
        'is_irregular': False,
        'frequency_rank': 77,
        'difficulty': 'beginner',
        'category': 'movement',
        'example_sentence': 'We moved to a new house.',
        'example_translation': 'Nos mudamos a una casa nueva.',
        'notes': 'Move = mover objeto. Move (house) = mudarse.'
    },
    {
        'infinitive': 'remember',
        'past_simple': 'remembered',
        'past_participle': 'remembered',
        'present_participle': 'remembering',
        'third_person': 'remembers',
        'spanish_translation': 'recordar',
        'is_irregular': False,
        'frequency_rank': 78,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I remember that day.',
        'example_translation': 'Recuerdo ese día.',
        'notes': 'Remember + to + inf = acordarse de hacer. Remember + gerundio = recordar haberlo hecho.'
    },
    {
        'infinitive': 'forget',
        'past_simple': 'forgot',
        'past_participle': 'forgotten',
        'present_participle': 'forgetting',
        'third_person': 'forgets',
        'spanish_translation': 'olvidar',
        'is_irregular': True,
        'frequency_rank': 79,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I forgot my keys.',
        'example_translation': 'Olvidé mis llaves.',
        'notes': 'Forget + to + inf = olvidar hacer algo.'
    },
    {
        'infinitive': 'understand',
        'past_simple': 'understood',
        'past_participle': 'understood',
        'present_participle': 'understanding',
        'third_person': 'understands',
        'spanish_translation': 'entender',
        'is_irregular': True,
        'frequency_rank': 80,
        'difficulty': 'beginner',
        'category': 'mental',
        'example_sentence': 'I understand now.',
        'example_translation': 'Ahora entiendo.',
        'notes': 'Verbo de estado - normalmente no se usa en continuo.'
    },
]

def seed_verbs():
    with app.app_context():
        # Verificar si ya hay verbos
        existing = Verb.query.count()
        if existing > 0:
            print(f"Ya existen {existing} verbos. ¿Desea eliminarlos y volver a crear? (s/n)")
            response = input().strip().lower()
            if response != 's':
                print("Operación cancelada.")
                return
            Verb.query.delete()
            db.session.commit()
            print("Verbos existentes eliminados.")
        
        # Agregar verbos
        count = 0
        for verb_data in verbs_data:
            verb = Verb(
                infinitive=verb_data['infinitive'],
                past_simple=verb_data['past_simple'],
                past_participle=verb_data['past_participle'],
                present_participle=verb_data['present_participle'],
                third_person=verb_data['third_person'],
                spanish_translation=verb_data['spanish_translation'],
                is_irregular=verb_data.get('is_irregular', False),
                is_modal=verb_data.get('is_modal', False),
                is_auxiliary=verb_data.get('is_auxiliary', False),
                frequency_rank=verb_data.get('frequency_rank'),
                difficulty=verb_data.get('difficulty', 'beginner'),
                category=verb_data.get('category'),
                example_sentence=verb_data.get('example_sentence'),
                example_translation=verb_data.get('example_translation'),
                notes=verb_data.get('notes')
            )
            db.session.add(verb)
            count += 1
        
        db.session.commit()
        print(f"✅ {count} verbos agregados exitosamente!")
        
        # Mostrar estadísticas
        irregulars = Verb.query.filter_by(is_irregular=True).count()
        regulars = Verb.query.filter_by(is_irregular=False).count()
        modals = Verb.query.filter_by(is_modal=True).count()
        print(f"   - Irregulares: {irregulars}")
        print(f"   - Regulares: {regulars}")
        print(f"   - Modales: {modals}")

if __name__ == '__main__':
    seed_verbs()
