"""Inicio limpio para produccion

Revision ID: 885678244c74
Revises: 
Create Date: 2026-07-13 21:17:15.984403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '885678244c74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_temas_orden'))
        batch_op.drop_index(batch_op.f('idx_temas_unidad'))

    op.drop_table('temas')
    with op.batch_alter_table('user_simulation_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_simulation_attempts_id'))
        batch_op.drop_index(batch_op.f('ix_user_simulation_attempts_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_user_simulation_attempts_user_id'))

    op.drop_table('user_simulation_attempts')
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_unidades_orden'))

    op.drop_table('unidades')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_course_category_active'))
        batch_op.drop_index(batch_op.f('idx_course_level'))
        batch_op.drop_index(batch_op.f('ix_courses_id'))
        batch_op.drop_index(batch_op.f('ix_courses_slug'))

    op.drop_table('courses')
    with op.batch_alter_table('course_simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_simulations_id'))
        batch_op.drop_index(batch_op.f('ix_course_simulations_lesson_id'))

    op.drop_table('course_simulations')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))
        batch_op.drop_index(batch_op.f('ix_admin_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_admin_users_role'))
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))

    op.drop_table('admin_users')
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_preguntas_tema'))

    op.drop_table('preguntas')
    with op.batch_alter_table('course_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_categories_id'))

    op.drop_table('course_categories')
    with op.batch_alter_table('course_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_exercises_id'))
        batch_op.drop_index(batch_op.f('ix_course_exercises_lesson_id'))

    op.drop_table('course_exercises')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_admin_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('user_course_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_course_progress'))
        batch_op.drop_index(batch_op.f('ix_user_course_progress_course_id'))
        batch_op.drop_index(batch_op.f('ix_user_course_progress_id'))
        batch_op.drop_index(batch_op.f('ix_user_course_progress_user_id'))

    op.drop_table('user_course_progress')
    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_modules_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_modules_id'))

    op.drop_table('course_modules')
    with op.batch_alter_table('course_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_certificates_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_certificates_id'))
        batch_op.drop_index(batch_op.f('ix_course_certificates_user_id'))

    op.drop_table('course_certificates')
    with op.batch_alter_table('admin_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_invites_email'))
        batch_op.drop_index(batch_op.f('ix_admin_invites_token'))

    op.drop_table('admin_invites')
    with op.batch_alter_table('user_exercise_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_exercise'))
        batch_op.drop_index(batch_op.f('ix_user_exercise_attempts_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_user_exercise_attempts_id'))
        batch_op.drop_index(batch_op.f('ix_user_exercise_attempts_user_id'))

    op.drop_table('user_exercise_attempts')
    with op.batch_alter_table('course_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_lessons_id'))
        batch_op.drop_index(batch_op.f('ix_course_lessons_module_id'))

    op.drop_table('course_lessons')
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lesson_progress_id'))
        batch_op.drop_index(batch_op.f('ix_user_lesson_progress_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_user_lesson_progress_user_id'))

    op.drop_table('user_lesson_progress')
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_sessions_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_sessions_is_active'))
        batch_op.drop_index(batch_op.f('ix_admin_sessions_session_token'))

    op.drop_table('admin_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('admin_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('admin_sessions_admin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_sessions_pkey'))
    )
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_sessions_session_token'), ['session_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_sessions_admin_id'), ['admin_id'], unique=False)

    op.create_table('user_lesson_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('time_spent_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], name=op.f('user_lesson_progress_lesson_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_lesson_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_lesson_progress_pkey')),
    sa.UniqueConstraint('user_id', 'lesson_id', name=op.f('uq_user_lesson'))
    )
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_lesson_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lesson_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lesson_progress_id'), ['id'], unique=False)

    op.create_table('course_lessons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], name=op.f('course_lessons_module_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_lessons_pkey')),
    sa.UniqueConstraint('module_id', 'order', name=op.f('uq_lesson_order'))
    )
    with op.batch_alter_table('course_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_lessons_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_lessons_id'), ['id'], unique=False)

    op.create_table('user_exercise_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_answer', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('score_earned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['course_exercises.id'], name=op.f('user_exercise_attempts_exercise_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_exercise_attempts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_exercise_attempts_pkey'))
    )
    with op.batch_alter_table('user_exercise_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_exercise_attempts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_exercise_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_exercise_attempts_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_exercise'), ['user_id', 'exercise_id'], unique=False)

    op.create_table('admin_invites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('used_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], name=op.f('admin_invites_created_by_fkey')),
    sa.ForeignKeyConstraint(['used_by_id'], ['admin_users.id'], name=op.f('admin_invites_used_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_invites_pkey'))
    )
    with op.batch_alter_table('admin_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_invites_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_invites_email'), ['email'], unique=False)

    op.create_table('course_certificates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificate_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('issued_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_certificates_course_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('course_certificates_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_certificates_pkey')),
    sa.UniqueConstraint('certificate_number', name=op.f('course_certificates_certificate_number_key'))
    )
    with op.batch_alter_table('course_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_certificates_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_certificates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_certificates_course_id'), ['course_id'], unique=False)

    op.create_table('course_modules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_modules_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_modules_pkey')),
    sa.UniqueConstraint('course_id', 'order', name=op.f('uq_module_order'))
    )
    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_modules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_modules_course_id'), ['course_id'], unique=False)

    op.create_table('user_course_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_spent_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('points_earned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('user_course_progress_course_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_course_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_course_progress_pkey')),
    sa.UniqueConstraint('user_id', 'course_id', name=op.f('uq_user_course'))
    )
    with op.batch_alter_table('user_course_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_course_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_course_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_course_progress_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_course_progress'), ['course_id', 'is_completed'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('audit_logs_admin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('course_exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('alternative_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], name=op.f('course_exercises_lesson_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_exercises_pkey'))
    )
    with op.batch_alter_table('course_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_exercises_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_exercises_id'), ['id'], unique=False)

    op.create_table('course_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('course_categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('course_categories_name_key'))
    )
    with op.batch_alter_table('course_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_categories_id'), ['id'], unique=False)

    op.create_table('preguntas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tema_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pregunta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('opcion_a', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('opcion_b', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('opcion_c', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('opcion_d', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('respuesta_correcta', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("respuesta_correcta = ANY (ARRAY['A'::bpchar, 'B'::bpchar, 'C'::bpchar, 'D'::bpchar])", name=op.f('preguntas_respuesta_correcta_check')),
    sa.ForeignKeyConstraint(['tema_id'], ['temas.id'], name=op.f('preguntas_tema_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('preguntas_pkey'))
    )
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_preguntas_tema'), ['tema_id'], unique=False)

    op.create_table('admin_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('failed_login_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('two_fa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('two_fa_secret', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_users_pkey'))
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    op.create_table('course_simulations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('simulation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scenario_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('correct_responses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lessons.id'], name=op.f('course_simulations_lesson_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_simulations_pkey'))
    )
    with op.batch_alter_table('course_simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_simulations_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_simulations_id'), ['id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cefr_level', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('duration_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_lessons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('price_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('preview_video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('learning_objectives', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('instructor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('instructor_bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instructor_avatar', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('students_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reviews_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_updated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('total_exercises_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['course_categories.id'], name=op.f('courses_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('courses_pkey')),
    sa.UniqueConstraint('slug', name=op.f('courses_slug_key'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('idx_course_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('idx_course_category_active'), ['category_id', 'is_active'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('unidades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icono', sa.VARCHAR(length=50), server_default=sa.text("'terminal'::character varying"), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('unidades_pkey'))
    )
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_unidades_orden'), ['orden'], unique=False)

    op.create_table('user_simulation_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('simulation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('responses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['course_simulations.id'], name=op.f('user_simulation_attempts_simulation_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_simulation_attempts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_simulation_attempts_pkey'))
    )
    with op.batch_alter_table('user_simulation_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_simulation_attempts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_simulation_attempts_simulation_id'), ['simulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_simulation_attempts_id'), ['id'], unique=False)

    op.create_table('temas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unidad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], name=op.f('temas_unidad_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('temas_pkey'))
    )
    with op.batch_alter_table('temas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_temas_unidad'), ['unidad_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_temas_orden'), ['orden'], unique=False)

    # ### end Alembic commands ###
