"""Add Thematic Scenarios tables

Revision ID: 9a761d6595be
Revises: a7b2f73d2472
Create Date: 2026-02-22 18:32:50.018062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a761d6595be'
down_revision = 'a7b2f73d2472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mini_game_contents', schema=None) as batch_op:
        batch_op.drop_column('age_group')

    with op.batch_alter_table('mini_games', schema=None) as batch_op:
        batch_op.drop_column('age_group')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('is_children_content')
        batch_op.drop_column('max_age')
        batch_op.drop_column('cefr_level')
        batch_op.drop_column('min_age')
        batch_op.drop_column('age_group')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('birth_date')
        batch_op.drop_column('parent_email')
        batch_op.drop_column('is_child')

    with op.batch_alter_table('vocabulary_items', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_child', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cefr_level', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_children_content', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('mini_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('mini_game_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
