"""Add last_login_date and daily_challenge_completed to User

Revision ID: a7b2f73d2472
Revises: 5ece6ea8332b
Create Date: 2026-02-16 20:19:21.121036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b2f73d2472'
down_revision = '5ece6ea8332b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('daily_challenge_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_challenge_completed')
        batch_op.drop_column('last_login_date')

    # ### end Alembic commands ###
