"""Agregando sistema de monetizacion, escenarios y zona de niños

Revision ID: ecde3a656fd9
Revises: 9a761d6595be
Create Date: 2026-02-22 18:44:39.315950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecde3a656fd9'
down_revision = '9a761d6595be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thematic_scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('price_points', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_expires_at')
        batch_op.drop_column('subscription_type')

    with op.batch_alter_table('thematic_scenarios', schema=None) as batch_op:
        batch_op.drop_column('price_points')
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
